#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Card_UI

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Card_UI.Card_UI_C.SetName
// 0x0018 (0x0018 - 0x0000)
struct Card_UI_C_SetName final
{
public:
	class FText                                   Name_0;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Card_UI_C_SetName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
